InventoryManagementApp/Controllers/TakeInventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryManagementApp.Data;
using InventoryManagementApp.Data.Models;
using InventoryManagementApp.Service;
using InventoryManagementApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InventoryManagementApp.Controllers
{
    public class TakeInventoryController : Controller
    {
        private InventoryService _inventoryService;

        public TakeInventoryController(InventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Title = "Take Inventory";

            #region Location Drop Down
            List<SelectListItem> locationDropDown = new List<SelectListItem>();
            List<Location> locations = _inventoryService.GetAllLocations();

            foreach (Location location in locations)
            {
                locationDropDown.Add(new SelectListItem() { Text = location.LocationName, Value = location.LocationKey.ToString() });
            }

            ViewBag.GetLocationDropDown = locationDropDown;
            #endregion

            #region Client Site Drop Down
            List<SelectListItem> clientSiteDropDown = new List<SelectListItem>();
            List<ClientSiteDTO> clientSites = _inventoryService.GetAllClientSites();

            foreach (ClientSiteDTO clientSite in clientSites)
            {
                clientSiteDropDown.Add(new SelectListItem() { Text = clientSite.ClientSiteName, Value = clientSite.ClientSiteKey.ToString() });
            }

            ViewBag.GetClientSiteDropDown = clientSiteDropDown;
            #endregion

            return View();
        }

        [HttpPost]
        public IActionResult Index(TakeInventoryVM selectedAsset)
        {
            ViewBag.Title = "Take Inventory";

            int assetKey = selectedAsset.AssetKey;
            AssetDTO fromDBAssetById = _inventoryService.GetAssetById(assetKey);

            //todo-fix the repeated DropDown code
            #region Location Drop Down
            List<SelectListItem> locationDropDown = new List<SelectListItem>();
            List<Location> locations = _inventoryService.GetAllLocations();

            foreach (Location location in locations)
            {
                locationDropDown.Add(new SelectListItem() { Text = location.LocationName, Value = location.LocationKey.ToString() });
            }

            ViewBag.GetLocationDropDown = locationDropDown;
            #endregion

            #region Client Site Drop Down
            List<SelectListItem> clientSiteDropDown = new List<SelectListItem>();
            List<ClientSiteDTO> clientSites = _inventoryService.GetAllClientSites();

            foreach (ClientSiteDTO clientSite in clientSites)
            {
                clientSiteDropDown.Add(new SelectListItem() { Text = clientSite.ClientSiteName, Value = clientSite.ClientSiteKey.ToString() });
            }

            ViewBag.GetClientSiteDropDown = clientSiteDropDown;
            #endregion

            if (fromDBAssetById == null)
            //can't find the assetKey, so return the _NotFound partial view
            {
                TakeInventoryVM userInput = new TakeInventoryVM();
                userInput.AssetKey = assetKey;
                return View(userInput);
            }
            //todo-todo-this needs to be put in a separate partial view I beleive. I.e. when the asset key is found, it needs to bring the table back as a partial, because it's a diffent model (takeInventoryVM and AssetDTO are differnt models)
            selectedAsset.ProductId = fromDBAssetById.ProductId;
            return View(selectedAsset);
        }

        public IActionResult ItemFoundGrid(int id)
        {
            AssetDTO fromDBAssetById = _inventoryService.GetAssetById(id);

            return View("_ItemFoundGrid", fromDBAssetById);
        }

        [HttpPost]
        public IActionResult CreateNewAsset(AssetDTO newAsset)
        {
            _inventoryService.SaveNewAsset(newAsset);

            //todo
            //try
            //{
            //    //
            //}catch (Exception e)
            //{
            //    throw new Exception(404, "CreateNewAssetMethodUseCaught");
            //}

            //todo-fix the repeated DropDown code
            #region Location Drop Down
            List<SelectListItem> locationDropDown = new List<SelectListItem>();
            List<Location> locations = _inventoryService.GetAllLocations();

            foreach (Location location in locations)
            {
                locationDropDown.Add(new SelectListItem() { Text = location.LocationName, Value = location.LocationKey.ToString() });
            }

            ViewBag.GetLocationDropDown = locationDropDown;
            #endregion

            #region Client Site Drop Down
            List<SelectListItem> clientSiteDropDown = new List<SelectListItem>();
            List<ClientSiteDTO> clientSites = _inventoryService.GetAllClientSites();

            foreach (ClientSiteDTO clientSite in clientSites)
            {
                clientSiteDropDown.Add(new SelectListItem() { Text = clientSite.ClientSiteName, Value = clientSite.ClientSiteKey.ToString() });
            }

            ViewBag.GetClientSiteDropDown = clientSiteDropDown;
            #endregion

            return View("Index");
        }

        [HttpGet]
        public IActionResult AddModifyItemModal(int id, TakeInventoryVM userDetails)
        {
            //when id  = 0, we are adding a new item
            //when id != 0, we are modifying an item
            AssetDTO asset = _inventoryService.GetAssetById(id);

            #region Product drop down
            //build Product drop down
            List<ProductDTO> products = _inventoryService.GetAllProductsDTO();

            List<SelectListItem> productDropdown = new List<SelectListItem>();
            foreach (ProductDTO p in products)
            {
                productDropdown.Add(new SelectListItem() { Text = p.ProductName, Value = p.ProductKey.ToString() });
            }

            ViewBag.GetProductDropDown = productDropdown;
            #endregion

            #region Manufacturer drop down
            //build Manufacturer drop down
            List<ManufacturerDTO> manufacturers = _inventoryService.GetAllManufacturersDTO();

            List<SelectListItem> manufacturerDropdown = new List<SelectListItem>();
            foreach (ManufacturerDTO m in manufacturers)
            {
                manufacturerDropdown.Add(new SelectListItem() { Text = m.ManufacturerName, Value = m.ManufacturerKey.ToString() });
            }

            ViewBag.GetManufacturerDropDown = manufacturerDropdown;
            #endregion

            #region Model drop down
            //build Model drop down
            List<ModelDTO> models = _inventoryService.GetAllModelsDTO();

            List<SelectListItem> modelDropdown = new List<SelectListItem>();
            foreach (ModelDTO m in models)
            {
                modelDropdown.Add(new SelectListItem() { Text = m.ModelName, Value = m.ModelKey.ToString() });
            }

            ViewBag.GetModelDropDown = modelDropdown;
            #endregion

            #region ClientSite Drop Down 
            //build client site DropDownList
            List<ClientSiteDTO> clientSites = _inventoryService.GetAllClientSites()
                                                               .Select(x => new ClientSiteDTO
                                                               {
                                                                   ClientSiteKey = x.ClientSiteKey,
                                                                   ClientSiteName = x.ClientSiteName
                                                               })
                                                               .ToList();

            List<SelectListItem> clientSiteDropdown = new List<SelectListItem>();
            foreach (ClientSiteDTO site in clientSites)
            {
                clientSiteDropdown.Add(new SelectListItem() { Text = site.ClientSiteName, Value = site.ClientSiteKey.ToString() });
            }

            ViewBag.GetClientSiteDropDown = clientSiteDropdown;
            #endregion

            //todo-fix the repeated DropDown code
            #region Location Drop Down
            List<SelectListItem> locationDropDown = new List<SelectListItem>();
            List<Location> locations = _inventoryService.GetAllLocations();

            foreach (Location location in locations)
            {
                locationDropDown.Add(new SelectListItem() { Text = location.LocationName, Value = location.LocationKey.ToString() });
            }

            ViewBag.GetLocationDropDown = locationDropDown;
            #endregion

            return PartialView("MyModal", asset ?? new AssetDTO());
            //return PartialView("_AddModifyItemModal", asset ?? new AssetDTO()); todo-delete
        }

        //[HttpGet]
        //public IActionResult MyModal(int id, TakeInventoryVM userDetails)
        //{
        //    //when id  = 0, we are adding a new item
        //    //when id != 0, we are modifying an item
        //    AssetDTO asset = _inventoryService.GetAssetById(id);

        //    #region Product drop down
        //    //build Product drop down
        //    List<ProductDTO> products = _inventoryService.GetAllProductsDTO();

        //    List<SelectListItem> productDropdown = new List<SelectListItem>();
        //    foreach (ProductDTO p in products)
        //    {
        //        productDropdown.Add(new SelectListItem() { Text = p.ProductName, Value = p.ProductKey.ToString() });
        //    }

        //    ViewBag.GetProductDropDown = productDropdown;
        //    #endregion

InventoryManagementApp/Views/TakeInventory/Index.cshtml
@model InventoryManagementApp.ViewModels.TakeInventoryVM

@Html.Display($"{ ViewBag.Title}")

@using (Html.BeginForm("Index", "TakeInventory", new { id = Model == null ? 0 : Model.AssetKey }))
{
    @Html.Label("Item:")
    @Html.TextBoxFor(m => m.AssetKey, new { placeholder = "Enter Asset Tag" })

    @Html.Label("Inventory Owner:")
    @Html.TextBoxFor(m => m.InventoryOwner, new { placeholder = "e.g. Arthur Dent" })

    @Html.Label("Location")
    @Html.DropDownListFor(m => m.LocationId, (List<SelectListItem>
    )ViewBag.GetLocationDropDown, "--Select Location--", new { @class = "form-control" })

    @Html.Label("Client Site:")
    @Html.DropDownListFor(m => m.ClientSiteId, (List<SelectListItem>)ViewBag.GetClientSiteDropDown, "--Select Client Site--", new { @class = "form-control" })

    <Button type="submit">Submit</Button> //todo I think this is supposed to be an onchangeevent not a submit button


    //todo take these out of the index page
    if (Model == null)
    {
        @Html.Partial("_StartScanningMsg")
    }
    if (Model != null && Model.AssetKey != null && Model.ProductId == 0)
    {
        @Html.Partial("_NotFound", Model)
    }
    if (Model != null && Model.AssetKey != null && Model.ProductId != 0)
    {
        @*@Html.Partial("_ItemFoundGrid", Model)*@
        @*@Html.Action("ItemFoundGrid", "TakeInventory", new { id = Model.AssetKey})*@
        @await Component.InvokeAsync("ItemFound", new { id = Model.AssetKey })
    }
}

@*todo-move these into the libraries*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>

InventoryManagementApp/Views/TakeInventory/MyModal.cshtml
@using InventoryManagementApp.Service
@model AssetDTO

<div class="modal fade" id="#addModifyItem">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Item</h4>
                <button type="button" class="close" data-dismiss="modal"><span>x</span></button>
            </div>
            <div class="modal-body">
                @*<form action="AddModifyItemModal" method="post">

        </form>*@
                @using (Html.BeginForm("AddModifyItemModal", "TakeInventory", FormMethod.Post, new { enctype = "multipart/form-data", id = Model.AssetKey }))
                {
                    @Html.LabelFor(a => a.AssetKey)
                    @Html.TextBoxFor(a => a.AssetKey)
                    <br />
                    @Html.LabelFor(a => a.Product)
                    @Html.DropDownListFor(a => a.ProductId, (List<SelectListItem>)ViewBag.GetProductDropDown, "--Select Product--")
                    <br />
                    @Html.LabelFor(a => a.Manuafcturer)
                    @Html.DropDownListFor(a => a.ManuafcturerId, (List<SelectListItem>)ViewBag.GetManufacturerDropDown, "--Select Manufacturer--")
                    <br />
                    @Html.LabelFor(a => a.Model)
                    @Html.DropDownListFor(a => a.ModelId, (List<SelectListItem>)ViewBag.GetModelDropDown, "--Select Model--")
                    <br />
                    @Html.LabelFor(a => a.Location)
                    @Html.DropDownListFor(a => a.LocationId, (List<SelectListItem>)ViewBag.GetLocationDropDown, "--Select Location--")
                    <br />
                    @Html.LabelFor(a => a.ClientSite)
                    @Html.DropDownListFor(a => a.ClientSiteId, (List<SelectListItem>)ViewBag.GetClientSiteDropDown, "--Select Client Site--")
                    <br />
                    @Html.LabelFor(a => a.SerialNumber)
                    @Html.TextBoxFor(a => a.SerialNumber)
                    <br />
                    @Html.LabelFor(a => a.ItemName)
                    @Html.TextBoxFor(a => a.ItemName)
                    <br />
                    @Html.LabelFor(a => a.PurchaseDate)
                    @Html.TextBoxFor(a => a.PurchaseDate, new { @class = "form-control datepicker" })
                    <br />
                    @Html.LabelFor(a => a.InventoryOwner)
                    @Html.TextBoxFor(a => a.InventoryOwner)
                    <br />
                    @Html.LabelFor(a => a.InventoriedBy)
                    @Html.TextBoxFor(a => a.InventoriedBy)
                    <br />
                    @Html.LabelFor(a => a.InventoryDate)
                    @Html.TextBoxFor(a => a.InventoryDate, new { @class = "form-control datepicker" })
                    <br />
                    @Html.LabelFor(a => a.IsDisposed)
                    @Html.CheckBoxFor(a => a.IsDisposed.Value)
                    <br />

                    @*<div>
                        <button type="submit">Submit</button>
                        <button type="reset">Cancel</button>
                    </div>*@
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-save="modal">Save</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

























<button id="btnShowModal" type="button"
        class="btn btn-sm btn-default pull-left col-lg-11 button button4">
    Add Item?
</button>

<div class="modal fade" tabindex="-1" id="addInventoryModal"
     data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Inventory</h4>
                <button type="button" class="close" data-dismiss="modal">
                    ×
                </button>
            </div>
            <div class="modal-body">
                @*<form>
                        <div class="form-group">
                            <input class="form-control" type="text"
                                   placeholder="Login Username" id="inputUserName" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Login Password"
                                   type="password" id="inputPassword" />
                        </div>
                    </form>*@
                @using (Html.BeginForm("AddModifyItemModal", "TakeInventory", FormMethod.Get, new { enctype = "multipart/form-data", id = Model.AssetKey }))
                {
                    //todo-add the _addModifyItemModal here
                    @Html.LabelFor(a => a.AssetKey, new { @class = "form-control" })
                    @Html.TextBoxFor(a => a.AssetKey, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(a => a.Product, new { @class = "form-control" })
                    @Html.DropDownListFor(a => a.ProductId, (List<SelectListItem>)ViewBag.GetProductDropDown, "--Select Product--", new { @class = "form-control" })

                }
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary button button4">Submit</button>
                <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                    Cancel
                </button>
            </div>
        </div>
    </div>
</div>


<footer>
    @*<p style="background-color: Yellow; font-weight: bold; color:blue; text-align: center; font-style: oblique">    </p>*@
</footer>
@*todo-move these into the libraries*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $("#btnShowModal").click(function () {
            $("#addInventoryModal").modal('show');
        });

        $("#btnHideModal").click(function () {
            $("#addInventoryModal").modal('hide');
        });
    });
</script> 

InventoryManagementApp/Views/TakeInventory/_AddModifyItemModal.cshtml
@using InventoryManagementApp.Service
@model AssetDTO
@*<head>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/datatables/css/dataTables.bootstrap.css" />
</head>*@

<div class=""></div>

Add Inventory
<button type="submit" class="btn btn-danger">Close button x</button>
@using (Html.BeginForm("AddModifyItemModal", "TakeInventory", FormMethod.Post, new { enctype = "multipart/form-data", id = Model.AssetKey }))
{
    @Html.LabelFor(a => a.AssetKey)
    @Html.TextBoxFor(a => a.AssetKey)
    <br />
    @Html.LabelFor(a => a.Product)
    @Html.DropDownListFor(a => a.ProductId, (List<SelectListItem>)ViewBag.GetProductDropDown, "--Select Product--")
    <br />
    @Html.LabelFor(a => a.Manuafcturer)
    @Html.DropDownListFor(a => a.ManuafcturerId, (List<SelectListItem>)ViewBag.GetManufacturerDropDown, "--Select Manufacturer--")
    <br />
    @Html.LabelFor(a => a.Model)
    @Html.DropDownListFor(a => a.ModelId, (List<SelectListItem>)ViewBag.GetModelDropDown, "--Select Model--")
    <br />
    @Html.LabelFor(a => a.Location)
    @Html.DropDownListFor(a => a.LocationId, (List<SelectListItem>)ViewBag.GetLocationDropDown, "--Select Location--")
    <br />
    @Html.LabelFor(a => a.ClientSite)
    @Html.DropDownListFor(a => a.ClientSiteId, (List<SelectListItem>)ViewBag.GetClientSiteDropDown, "--Select Client Site--")
    <br />
    @Html.LabelFor(a => a.SerialNumber)
    @Html.TextBoxFor(a => a.SerialNumber)
    <br />
    @Html.LabelFor(a => a.ItemName)
    @Html.TextBoxFor(a => a.ItemName)
    <br />
    @Html.LabelFor(a => a.PurchaseDate)
    @Html.TextBoxFor(a => a.PurchaseDate, new { @class = "form-control datepicker" })
    <br />
    @Html.LabelFor(a => a.InventoryOwner)
    @Html.TextBoxFor(a => a.InventoryOwner)
    <br />
    @Html.LabelFor(a => a.InventoriedBy)
    @Html.TextBoxFor(a => a.InventoriedBy)
    <br />
    @Html.LabelFor(a => a.InventoryDate)
    @Html.TextBoxFor(a => a.InventoryDate, new { @class = "form-control datepicker" })
    <br />
    @Html.LabelFor(a => a.IsDisposed)
    @Html.CheckBoxFor(a => a.IsDisposed.Value)
    <br />

    <div>
        <button type="submit">Submit</button>
        <button type="reset">Cancel</button>
    </div>
}

<script src="/lib/jquery/jquery.js"></script>
<script src="/lib/bootstrap/js/bootstrap.js"></script>

InventoryManagementApp/Views/TakeInventory/_Details.cshtml
<div>

    <div class="modal-header">
        <button type="button" id="closbtn" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">FriendsInfo</h4>
    </div>

    <p>some text SS</p>
</div>

InventoryManagementApp/Views/TakeInventory/_NotFound.cshtml
@model InventoryManagementApp.ViewModels.TakeInventoryVM

<br />
<br />
<br />

@Html.Label($"Item {Model.AssetKey} Not Found") @*todo-make red, new { @class = "text-danger"})*@

<button type="submit" formaction=@Url.Action("AddModifyItemModal") formmethod="get">Add Item?</button>  @*n.b. this button is for the form in the TakeInventory folder's Index.cshtml page*@
<button class="text-danger">Cancel?</button>

@*<input type="submit" value="submit!" onclick="@Url.Action("CreateNewAsset", "TakeInventory")" />*@

<input type="submit" value="todo: move me into the modal!" formaction=@Url.Action("CreateNewAsset") />

<input type="submit" value ="Add Item?" id="modalShow" formaction=@Url.Action("MyModal") formmethod="get"/>

@*<button id="btnShowModal" type="button"
        class="btn btn-sm btn-default pull-left col-lg-11 button button4">
    Add Item?
</button>*@

<div id="Placeholder"></div>

<button id="ssButton" type="button"class="btn btn-primary" data-toggle="ajax-modal" data-target="#addModifyItem" data-url="@Url.Action("AddModifyItemModal")">Add Item?</button>

InventoryManagementApp/Views/TakeInventory/_StartPage.cshtml
<br />
<br />

<p>Scan each item at this location.</p>
<p>A laser scanner can be used to perform the inventory but it must be configured to add a carriage return at the end of the scan.</p>

InventoryManagementApp/Views/TakeInventory/_StartScanningMsg.cshtml
<br />
<br />

<p>Scan each item at this location.</p>
<p>A laser scanner can be used to perform the inventory but it must be configured to add a carriage return at the end of the scan.</p>